server:
    port: 0

spring:
    application:
        name: price-service
    mvc:
        log-request-details: true
    cloud:
        #consul:
         #   host: ${consul.host:localhost}
          #  port: ${consul.port:8500}
        loadbalancer:
            ribbon:
                enabled: false
management:
    endpoints:
        web:
            exposure:
                include: "*"

logging:
    level:
        com.emirates: INFO
        org.springframework.web: INFO